// Autogenerated by Thrift Compiler (0.12.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package main

import (
        "context"
        "flag"
        "fmt"
        "math"
        "net"
        "net/url"
        "os"
        "strconv"
        "strings"
        "github.com/apache/thrift/lib/go/thrift"
	"bfss/utils"
        "bfss/bfss_regm"
)

var _ = utils.GoUnusedProtection__

func Usage() {
  fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
  flag.PrintDefaults()
  fmt.Fprintln(os.Stderr, "\nFunctions:")
  fmt.Fprintln(os.Stderr, "  string GetVersion()")
  fmt.Fprintln(os.Stderr, "  MESSAGE_RESULT ManageMessage(BFSS_CMD CmdId, i32 Param, string Data)")
  fmt.Fprintln(os.Stderr, "  BFSS_RESULT RegisterVolume(REGISTER_VOLUME_INFO VolumeInfo)")
  fmt.Fprintln(os.Stderr, "  BFSS_RESULT UpdateVolume(UPDATE_VOLUME_STATUS Status)")
  fmt.Fprintln(os.Stderr, "  VOLUME_RESULT GetVolumeInfo(i32 VolumeId)")
  fmt.Fprintln(os.Stderr, "  ALL_VOLUME_RESULT GetAllVolumeInfo()")
  fmt.Fprintln(os.Stderr, "  ALLOCATED_RESULT AllocateBlks(i32 size)")
  fmt.Fprintln(os.Stderr, "  BFSS_RESULT AddBlkChip(ALLOCATED_INFO Allocated_info)")
  fmt.Fprintln(os.Stderr)
  os.Exit(0)
}

type httpHeaders map[string]string

func (h httpHeaders) String() string {
  var m map[string]string = h
  return fmt.Sprintf("%s", m)
}

func (h httpHeaders) Set(value string) error {
  parts := strings.Split(value, ": ")
  if len(parts) != 2 {
    return fmt.Errorf("header should be of format 'Key: Value'")
  }
  h[parts[0]] = parts[1]
  return nil
}

func main() {
  flag.Usage = Usage
  var host string
  var port int
  var protocol string
  var urlString string
  var framed bool
  var useHttp bool
  headers := make(httpHeaders)
  var parsedUrl *url.URL
  var trans thrift.TTransport
  _ = strconv.Atoi
  _ = math.Abs
  flag.Usage = Usage
  flag.StringVar(&host, "h", "localhost", "Specify host and port")
  flag.IntVar(&port, "p", 9090, "Specify port")
  flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
  flag.StringVar(&urlString, "u", "", "Specify the url")
  flag.BoolVar(&framed, "framed", false, "Use framed transport")
  flag.BoolVar(&useHttp, "http", false, "Use http")
  flag.Var(headers, "H", "Headers to set on the http(s) request (e.g. -H \"Key: Value\")")
  flag.Parse()
  
  if len(urlString) > 0 {
    var err error
    parsedUrl, err = url.Parse(urlString)
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
    host = parsedUrl.Host
    useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http" || parsedUrl.Scheme == "https"
  } else if useHttp {
    _, err := url.Parse(fmt.Sprint("http://", host, ":", port))
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
  }
  
  cmd := flag.Arg(0)
  var err error
  if useHttp {
    trans, err = thrift.NewTHttpClient(parsedUrl.String())
    if len(headers) > 0 {
      httptrans := trans.(*thrift.THttpClient)
      for key, value := range headers {
        httptrans.SetHeader(key, value)
      }
    }
  } else {
    portStr := fmt.Sprint(port)
    if strings.Contains(host, ":") {
           host, portStr, err = net.SplitHostPort(host)
           if err != nil {
                   fmt.Fprintln(os.Stderr, "error with host:", err)
                   os.Exit(1)
           }
    }
    trans, err = thrift.NewTSocket(net.JoinHostPort(host, portStr))
    if err != nil {
      fmt.Fprintln(os.Stderr, "error resolving address:", err)
      os.Exit(1)
    }
    if framed {
      trans = thrift.NewTFramedTransport(trans)
    }
  }
  if err != nil {
    fmt.Fprintln(os.Stderr, "Error creating transport", err)
    os.Exit(1)
  }
  defer trans.Close()
  var protocolFactory thrift.TProtocolFactory
  switch protocol {
  case "compact":
    protocolFactory = thrift.NewTCompactProtocolFactory()
    break
  case "simplejson":
    protocolFactory = thrift.NewTSimpleJSONProtocolFactory()
    break
  case "json":
    protocolFactory = thrift.NewTJSONProtocolFactory()
    break
  case "binary", "":
    protocolFactory = thrift.NewTBinaryProtocolFactoryDefault()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
    Usage()
    os.Exit(1)
  }
  iprot := protocolFactory.GetProtocol(trans)
  oprot := protocolFactory.GetProtocol(trans)
  client := bfss_regm.NewBFSS_REGMDClient(thrift.NewTStandardClient(iprot, oprot))
  if err := trans.Open(); err != nil {
    fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
    os.Exit(1)
  }
  
  switch cmd {
  case "GetVersion":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetVersion requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetVersion(context.Background()))
    fmt.Print("\n")
    break
  case "ManageMessage":
    if flag.NArg() - 1 != 3 {
      fmt.Fprintln(os.Stderr, "ManageMessage requires 3 args")
      flag.Usage()
    }
    tmp0, err := (strconv.Atoi(flag.Arg(1)))
    if err != nil {
      Usage()
     return
    }
    argvalue0 := bfss_regm.BFSS_CMD(tmp0)
    value0 := argvalue0
    tmp1, err19 := (strconv.Atoi(flag.Arg(2)))
    if err19 != nil {
      Usage()
      return
    }
    argvalue1 := int32(tmp1)
    value1 := argvalue1
    argvalue2 := []byte(flag.Arg(3))
    value2 := argvalue2
    fmt.Print(client.ManageMessage(context.Background(), value0, value1, value2))
    fmt.Print("\n")
    break
  case "RegisterVolume":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "RegisterVolume requires 1 args")
      flag.Usage()
    }
    arg21 := flag.Arg(1)
    mbTrans22 := thrift.NewTMemoryBufferLen(len(arg21))
    defer mbTrans22.Close()
    _, err23 := mbTrans22.WriteString(arg21)
    if err23 != nil {
      Usage()
      return
    }
    factory24 := thrift.NewTJSONProtocolFactory()
    jsProt25 := factory24.GetProtocol(mbTrans22)
    argvalue0 := bfss_regm.NewREGISTER_VOLUME_INFO()
    err26 := argvalue0.Read(jsProt25)
    if err26 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.RegisterVolume(context.Background(), value0))
    fmt.Print("\n")
    break
  case "UpdateVolume":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "UpdateVolume requires 1 args")
      flag.Usage()
    }
    arg27 := flag.Arg(1)
    mbTrans28 := thrift.NewTMemoryBufferLen(len(arg27))
    defer mbTrans28.Close()
    _, err29 := mbTrans28.WriteString(arg27)
    if err29 != nil {
      Usage()
      return
    }
    factory30 := thrift.NewTJSONProtocolFactory()
    jsProt31 := factory30.GetProtocol(mbTrans28)
    argvalue0 := bfss_regm.NewUPDATE_VOLUME_STATUS()
    err32 := argvalue0.Read(jsProt31)
    if err32 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.UpdateVolume(context.Background(), value0))
    fmt.Print("\n")
    break
  case "GetVolumeInfo":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetVolumeInfo requires 1 args")
      flag.Usage()
    }
    tmp0, err33 := (strconv.Atoi(flag.Arg(1)))
    if err33 != nil {
      Usage()
      return
    }
    argvalue0 := int32(tmp0)
    value0 := argvalue0
    fmt.Print(client.GetVolumeInfo(context.Background(), value0))
    fmt.Print("\n")
    break
  case "GetAllVolumeInfo":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetAllVolumeInfo requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetAllVolumeInfo(context.Background()))
    fmt.Print("\n")
    break
  case "AllocateBlks":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "AllocateBlks requires 1 args")
      flag.Usage()
    }
    tmp0, err34 := (strconv.Atoi(flag.Arg(1)))
    if err34 != nil {
      Usage()
      return
    }
    argvalue0 := int32(tmp0)
    value0 := argvalue0
    fmt.Print(client.AllocateBlks(context.Background(), value0))
    fmt.Print("\n")
    break
  case "AddBlkChip":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "AddBlkChip requires 1 args")
      flag.Usage()
    }
    arg35 := flag.Arg(1)
    mbTrans36 := thrift.NewTMemoryBufferLen(len(arg35))
    defer mbTrans36.Close()
    _, err37 := mbTrans36.WriteString(arg35)
    if err37 != nil {
      Usage()
      return
    }
    factory38 := thrift.NewTJSONProtocolFactory()
    jsProt39 := factory38.GetProtocol(mbTrans36)
    argvalue0 := bfss_regm.NewALLOCATED_INFO()
    err40 := argvalue0.Read(jsProt39)
    if err40 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.AddBlkChip(context.Background(), value0))
    fmt.Print("\n")
    break
  case "":
    Usage()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
  }
}
